name: Deploy

on:
  push:
    tags:
      - '*.*.*'

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version From Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Setup Terraform Variables
        working-directory: ./infra
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          sem_ver = "${{ steps.vars.outputs.tag }}"
          EOF
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: infra
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infra
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: infra
      - name: Release
        uses: softprops/action-gh-release@v1
